"""add metadata_json to publications

Revision ID: a8d5963e425b
Revises: add_gin_index_abstract
Create Date: 2025-12-28 20:08:04.044281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8d5963e425b'
down_revision: Union[str, Sequence[str], None] = 'add_gin_index_abstract'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publications', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('publications', 'abstract',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_publications_abstract_gin'), table_name='publications', postgresql_ops={'(abstract::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_publications_title'), table_name='publications')
    op.drop_constraint(op.f('publications_doi_key'), 'publications', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('publications_doi_key'), 'publications', ['doi'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_publications_title'), 'publications', ['title'], unique=False)
    op.create_index(op.f('ix_publications_abstract_gin'), 'publications', [sa.literal_column('(abstract::text)')], unique=False, postgresql_ops={'(abstract::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('publications', 'abstract',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('publications', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
